### ISSUE TITLE
Error when following instructions for preprocessing the QM9 datasets.

### ISSUE THREAD

**Issue by williamnyren** [JosieHong/3DMolMS#2]
Followed instructions for pretraining with QM9 dataset downloaded from [here](https://figshare.com/collections/Quantum_chemistry_structures_and_properties_of_134_kilo_molecules/978904) 
 (https://figshare.com/collections/Quantum_chemistry_structures_and_properties_of_134_kilo_molecules/978904)

Issue:
`qm92pkl.py` does't run as intended.

When running  `def xyz2dict(xyz_dir)`  an error occurs error:

> AttributeError: module 'numpy' has no attribute 'float'

The specific line:
`pkl_list.append({'title': file_name, 'smiles': smiles, 'y': np.array(scalar_prop[3:16], dtype=np.float)})`

Fix?
`pkl_list.append({'title': file_name, 'smiles': smiles, 'y': np.array(scalar_prop[3:16], dtype=np.float64)})`

**Comment by JosieHong** [comment]
Referring to this answer: https://stackoverflow.com/a/74861894: 

- NumPy 1.20 [(release notes)](https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations) deprecated `numpy.float`, `numpy.int`, and similar aliases, causing them to issue a deprecation warning
- NumPy 1.24 [(release notes)](https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations) removed these aliases altogether, causing an error when they are used

So, `pkl_list.append({'title': file_name, 'smiles': smiles, 'y': np.array(scalar_prop[3:16], dtype=float)})` should solve the error. Or you could downgrade the NumPy to a version < 1.24. 

Thanks for letting me know that! I will give the version of NumPy I used (1.21.5) in `requirements.txt`.
