### ISSUE TITLE
all2pkl.py: Pandas import, undefined functions

### ISSUE THREAD

**Issue by Michael-C-Strobel** [JosieHong/3DMolMS#6]
Hello, I'm trying to use the main branch code to perform some inferences over a few molecules and I'm running into issues when providing a csv input. It seems that `all2pkl.py` is missing an `import pandas as pd` along with a definition or import for `ce2nce`.

Thanks!

**Comment by JosieHong** [comment]
Thank you so much! I made a quick fix. Please let me know if there are any other problems.

**Comment by Michael-C-Strobel** [comment]
Hello, thank you very much for the quick response. Everything seems to be working on my end. I will close the issue.
