### ISSUE TITLE
Possibility for application on GC-MS spectrum?

### ISSUE THREAD

**Issue by jcwang587** [JosieHong/3DMolMS#7]
Hi @JosieHong, thank you for sharing this great package! I was wondering if the model could be adapted for GC-MS spectra. Is it possible to train the model using only the spectrum data, without including the precursor types and collision energies? Thank you!

**Comment by JosieHong** [comment]
Yes, for sure. You can check the configurations in `./src/molnetpack/config/molnet.yml` and set `add_num` to 0 instead of 6, and then input `None` as `env` during training and testing. I’d be happy to help if you encounter any further issues. Thanks!

**Comment by jcwang587** [comment]
Thank you for the instructions and quick response!
